set_property SRC_FILE_INFO {cfile:/home/ryunosuke/Works/zynqberrydemo1/test/config.xdc rfile:../../../../../test/config.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H11 [get_ports test_in]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G11 [get_ports test_out]
